# -*- coding: utf-8 -*-

"""
    tests.controllers.test_channel_controller

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import jsonpickle
import dateutil.parser
from .controller_test_base import ControllerTestBase
from ..test_helper import TestHelper
from akkblfpim23.api_helper import APIHelper


class ChannelControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(ChannelControllerTests, cls).setUpClass()
        cls.controller = cls.api_client.channel

    # Assuming that the given code is the code of an existing channel
    def test_channel(self):

        # Perform the API call through the SDK function
        self.controller.get_channel()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # TODO: Add Description
    def test_channels(self):

        # Perform the API call through the SDK function
        self.controller.get_channels()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

