# -*- coding: utf-8 -*-

"""
    tests.controllers.test_attribute_option_controller

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import jsonpickle
import dateutil.parser
from .controller_test_base import ControllerTestBase
from ..test_helper import TestHelper
from akkblfpim23.api_helper import APIHelper


class AttributeOptionControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(AttributeOptionControllerTests, cls).setUpClass()
        cls.controller = cls.api_client.attribute_option

    # Assuming that the given codes are respectively the code of an existing attribute and an existing option of this attribute
    def test_attribute_option(self):

        # Perform the API call through the SDK function
        self.controller.get_attribute_option()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # TODO: Add Description
    def test_attribute_options(self):

        # Perform the API call through the SDK function
        self.controller.get_attribute_options()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

