# -*- coding: utf-8 -*-

"""
    tests.controllers.test_product_controller

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import jsonpickle
import dateutil.parser
from .controller_test_base import ControllerTestBase
from ..test_helper import TestHelper
from akkblfpim23.api_helper import APIHelper


class ProductControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(ProductControllerTests, cls).setUpClass()
        cls.controller = cls.api_client.product

    # Assuming that the given identifier is the identifier of an existing product
    def test_product(self):

        # Perform the API call through the SDK function
        self.controller.get_product()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # 
    #
    def test_products(self):
        # Parameters for the API call
        content_type = 'application/json'
        cookie = ''

        # Perform the API call through the SDK function
        self.controller.get_products(content_type, cookie)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

