# -*- coding: utf-8 -*-

"""
    tests.controllers.test_family_controller

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import jsonpickle
import dateutil.parser
from .controller_test_base import ControllerTestBase
from ..test_helper import TestHelper
from akkblfpim23.api_helper import APIHelper


class FamilyControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(FamilyControllerTests, cls).setUpClass()
        cls.controller = cls.api_client.family

    # Assuming that the given code is the code of an existing family
    def test_family(self):

        # Perform the API call through the SDK function
        self.controller.get_family()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # TODO: Add Description
    def test_families(self):

        # Perform the API call through the SDK function
        self.controller.get_families()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

