# -*- coding: utf-8 -*-

"""
    akkblfpim23.models.authentification_by_refresh_token_request

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""


class AuthentificationByRefreshTokenRequest(object):

    """Implementation of the 'Authentification by refresh tokenRequest' model.

    TODO: type model description here.

    Attributes:
        refresh_token (string): TODO: type description here.
        grant_type (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "refresh_token":'refresh_token',
        "grant_type":'grant_type'
    }

    def __init__(self,
                 refresh_token=None,
                 grant_type=None):
        """Constructor for the AuthentificationByRefreshTokenRequest class"""

        # Initialize members of the class
        self.refresh_token = refresh_token
        self.grant_type = grant_type


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        refresh_token = dictionary.get('refresh_token')
        grant_type = dictionary.get('grant_type')

        # Return an object of this model
        return cls(refresh_token,
                   grant_type)


